# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이동준
title: Machine Learning Engineer
email: scvzl6011@gmail.com
# website: https://velog.io/@djlee6011

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: hyanghoa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: velog
  icon: fas fa-globe
  url: https://velog.io/@djlee6011
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  웹 서비스 백엔드 개발과 스타트업 개발자로서의 다양한 경험이 있습니다.
  
  Django, MySQL, PostgreSQL, Pytorch, Python, Git, Linux 등을 사용하여 서비스를 설계, 개발한 경험으로
  
  다른 동료들과 함께 협업하기 쉬울 수 있도록 가독성 좋은 클린한 코드를 만들고,
  
  확장성과 유지 보수가 잘 될 수 있는 코드를 위해 노력하고 있습니다.

  Skill: <mark>Django</mark> <mark>MySQL</mark> <mark>PostgreSQL</mark> <mark>Pytorch</mark> <mark>Python</mark> <mark>Git</mark> <mark>Linux</mark>

content:
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning
        description: | # this will include new lines to allow paragraphs
          - Pytorch
          - Pandas
          - Numpy
          - Scikit-learn
          - Opencv-python
          - jupyter

      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Django
      
      - layout: left
        title: DB
        description: | # this will include new lines to allow paragraphs
          - PostgreSQM
          - MySQL

      - layout: left
        title: Etc
        description: | # this will include new lines to allow paragraphs
          - Ubuntu
          - Docker
          - Git / Github
          - Vim
          - VS Code
          - Redmine
          - Slack

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아임토리
        link: https://www.aimtory.com
        # link_text: boringcompany.com
        sub_title: 이미지 AI 개발자
        caption: 2022.08 - 현재
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            웹 개발
            - 대시보드 확인 가능
            - 학습 및 추론 가능

            모델 통합 프레임워크 개발
            - MVTecAD 데이터셋 벤치마크 상위권 모델들과 self-supervised learning을 적용해서 전체 학습 및 결과 확인
            - optuna를 적용해서 자동 하이퍼파라미터 탐색할 수 있도록 적용

            생산기지 BOG 최적가동 예측 모델 개발 경진대회
            - [BOG 최적가동 예측 부문 스타트업 최우수상](https://aifactory.space/competition/detail/2105)
            - [기사](https://news.mt.co.kr/mtview.php?no=2022121513031813723)

            논문 리뷰
            - 이미지 및 비디오, self-supervised learning

            코드 적용
            - Image Anomaly Detection 모델에 self-supervised learning 적용

      - layout: left
        title: 써로마인드
        link: https://surromind.ai
        # link_text: boringcompany.com
        sub_title: 머신러닝 엔지니어
        caption: 2020.10 - 2021.07
        # quote: >
        # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            AI Web Platform:
            - 데이터 어노테이션, 전처리부터, 학습 및 추론까지 할 수 있는 웹

            교통안전
            - 사람 얼굴 방향 분류, 스마트 폰 및 담배 디텍션 교통안전 정부과제

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코스포 x 데이콘 자동차 충돌 분석 AI경진대회
        sub_title: 데이콘
        # link: https://github.com/hyanghoa/dacon_tool/blob/main/code_similarity/baseline_pytorch.ipynb
        # link_text: jupyter notebook link
        additional_links:
          - title:  jupyter notebook
            icon: fab fa-github
            url: https://github.com/hyanghoa/dacon_tool/blob/main/car_crash/baseline.ipynb
          - title:  leaderboard
            icon: fas fa-globe
            url: https://dacon.io/competitions/official/236064/leaderboard
        quote: >
          블랙박스 영상의 자동차 충돌 분석 AI 알고리즘 개발
        description: | # this will include new lines to allow paragraphs
          10프레임, 5초 분량의 블랙박스 영상(mp4)들을 입력으로 받아 자동차 충돌 상황을 분석하여,

          이를 13가지 상황(Class)으로 분류하는 AI 모델을 개발하는 대회입니다.
          
          차량 충돌 상황에 따라 충돌 여부(yes, no), 사고 휘말린 여부(yes, no), 날씨(normal, snow, rainy), 시간(낮/밤)으로
          
          작은 task로 각각 classification 모델을 만들었습니다.
          
          pre-trained 모델은 MViTv2-S를 사용했습니다.

          Result

          순위: <mark>31/449</mark>

          상위: <mark>10%</mark>

          Model: <mark>MViTv2-S</mark>

      - layout: left
        title: 자율주행 센서의 안테나 성능 예측 AI 경진대회
        sub_title: 데이콘
        # link: https://github.com/hyanghoa/dacon_tool/blob/main/code_similarity/baseline_pytorch.ipynb
        # link_text: jupyter notebook link
        additional_links:
          - title:  leaderboard
            icon: fas fa-globe
            url: https://dacon.io/competitions/official/235927/leaderboard
        quote: >
          공정 데이터를 활용하여 Radar 센서의 안테나 성능 예측을 위한 AI 모델 개발
        description: | # this will include new lines to allow paragraphs
          tabular 데이터를 이용해서 예측하는 대회입니다.

          모델은 LightGBM을 사용했습니다.

          Result

          순위: <mark>26/975</mark>

          상위: <mark>3%</mark>

          Model: <mark>LightGBM</mark>

      - layout: left
        title: 코드 유사성 판단 AI 경진대회
        sub_title: 데이콘
        # link: https://github.com/hyanghoa/dacon_tool/blob/main/code_similarity/baseline_pytorch.ipynb
        # link_text: jupyter notebook link
        additional_links:
          - title:  jupyter notebook
            icon: fab fa-github
            url: https://github.com/hyanghoa/dacon_tool/blob/main/code_similarity/baseline_pytorch.ipynb
          - title:  leaderboard
            icon: fas fa-globe
            url: https://dacon.io/competitions/official/235900/leaderboard
        quote: >
          두 코드간 유사성(동일 결과물 산출 가능한지) 여부를 판단할 수 있는 AI 알고리즘을 개발
        description: | # this will include new lines to allow paragraphs
          주어진 두개의 코드 스크립트를 비교해서 같은 결과를 가질 수 있는지 판단하는 인공지능 모델을 개발하는 대회입니다.
          
          코드에서 주석이나 import 같은 의미 없는 부분을 제거하는 등의 전처리를 적용했고,
          
          제일 비슷한 환경에서 학습된 GraphCodeBERT를 사용했습니다.

          Result

          순위: <mark>16/337</mark>

          상위: <mark>10%</mark>

          Model: <mark>GraphCodeBERT</mark>
      
      - layout: left
        title: Computer Vision 이상치 탐지 알고리즘 경진대회
        sub_title: 데이콘
        # link: https://github.com/hyanghoa/dacon_tool/blob/main/anomaly-classification/baseline.ipynb
        # link_text: jupyter notebook link
        additional_links:
          - title:  jupyter notebook
            icon: fab fa-github
            url: https://github.com/hyanghoa/dacon_tool/blob/main/anomaly-classification/baseline.ipynb
          - title:  leaderboard
            icon: fas fa-globe
            url: https://dacon.io/competitions/official/235894/leaderboard
        quote: >
          사물의 종류를 분류하고, 정상 샘플과 비정상(이상치) 샘플을 분류
        description: | # this will include new lines to allow paragraphs
          MVTecAD 데이터셋이 주어지고, 각각의 클래스의 정상 및 여러가지 비정상 종류를 분류하는 모델을 개발하는 대회입니다.
          
          여러가지 backbone을 사용해본 결과 EfficientNet이 제일 성능이 좋았고,
          
          정상과 비정상 클래스간 불균형을 해결하기 위한 방법으로 TADE 기법을 적용했습니다.

          Result

          순위: <mark>15/481</mark>

          상위: <mark>4%</mark>

          Model: <mark>Efficientnetv2-m</mark>

      - layout: left
        title: 작물 병해 분류 AI 경진대회
        sub_title: 데이콘
        additional_links:
          - title:  leaderboard
            icon: fas fa-globe
            url: https://dacon.io/competitions/official/235842/leaderboard
        quote: >
          병해 판별 및 처방에 도움을 줄 수 있는 인공지능 기술 개발
        description: | # this will include new lines to allow paragraphs
          병해 피해를 입은 작물 사진을 통해 병해를 진단할 수 있는 모델을 개발하는 대회입니다.

          미세한 부분까지 잘 잡아낼 수 있는 Swin transformer를 채용해서 학습을 했습니다.

          Result

          순위: <mark>13/170</mark>

          상위: <mark>10%</mark>

          Model: <mark>Swin transformer</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 산업융합형 인공지능 청년혁신가 양성과정
        caption: 2020.05 - 2020.11
        sub_title: 한국표준협회
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          인공지능에 대해서 배우는 과정입니다.

          기초적인 C, Java, Python 프로그래밍 언어와,

          서버를 구축하는 방법, 머신러닝과 딥러닝 이론, 이미지 처리방법에 대해서 배우는 과정입니다.
      
      - layout: left
        title: 드론을 활용한 IoT 고급 인재 양성 과정
        caption: 2019.09 - 2019.11
        sub_title: 한국소프트웨어산업협회
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - [시연 영상](https://drive.google.com/file/d/1LIV8BPOWmGjsjz0nctvDoHR8iXIrVXzq/view)

          이 과정을 통해서 "드론을 활용한 화재 초기진압 및 정찰" 이라는 프로젝트를 진행했었습니다.

          화재를 발견한 사람이 저희가 만든 웹을 통해서 화재 위치를 지도에서 찍고 신고를 할 수 있고,

          신고를 받은 관리자 웹페이지 화면에서 드론으로 다시 데이터를 보내고,

          GCS 프로그램을 통해서 드론을 조종해서 화재위치로 이동 할 수 있는 프로젝트입니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
